services:
    db:
        image: postgres
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_DB=nerdhub_db
            - POSTGRES_PASSWORD=nerdhub
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - 5432:5432
        volumes:
            - ./data/postgres:/var/lib/postgresql/data/pgdata

    adminer:
        image: adminer
        restart: always
        ports:
            - 8081:8080
    